// <auto-generated />
namespace PublicTransportGallery.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changenametbllogvisitorimages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changenametbllogvisitorimages));
        
        string IMigrationMetadata.Id
        {
            get { return "201908310953330_change name tbllogvisitorimages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
