//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicTransportGallery.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblImage
    {
        public int ImageId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> ProducentId { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string Id { get; set; }
    
        public virtual TblModel TblModel { get; set; }
        public virtual TblProducent TblProducent { get; set; }
    }
}
